---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
        types: [file]
        files: .*(\.ini)$
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, -c, .yamllint]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        entry: shellcheck --shell=bash
  - repo: local
    hooks:
      - id: mbake-format
        name: mbake formatter
        entry: mbake format --config .bake.toml
        language: system
        types: [makefile]
      - id: check-pip-freeze
        name: Generate pip requirements
        entry: ./hooks/pip-freeze.sh
        language: system
      - id: format-kitty-conf
        name: Format kitty.conf
        entry: hooks/format-kitty.py
        language: system
        files: .*kitty\.conf$
        types: [file]
      - id: format-mako-conf
        name: Format mako
        entry: hooks/format-mako.py
        language: system
        files: .*(mako|mako/config)$
        types: [file]
      - id: ansible-lint
        name: Lint ansible files
        entry: ./hooks/ansible-lint.sh
        language: system
        files: ^ansible/(roles|playbooks/inventory|ansible\.cfg|requirements.txt).*$
        types: [file]
