[config]

[templates.waybar]
input_path = './templates/colors.css.tpl'
output_path = '~/.config/waybar/generated-colors-matugen.css'

[templates.rofi]
input_path = './templates/rofi.rasi.tpl'
output_path = '~/.config/rofi/themes/generated-colors-matugen.rasi'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/generated-colors-matugen.conf'

[templates.hypr]
input_path = './templates/hypr.conf.tpl'
output_path = '~/.config/hypr/config.d/generated-colors-matugen.conf'

[templates.tmux]
input_path = './templates/tmux.tpl'
output_path = '~/.config/tmux/generated-colors-matugen.conf'

[templates.mako]
input_path = './templates/mako.tpl'
output_path = '~/.config/mako/generated-colors-matugen.conf'

[templates.firefox]
input_path = './templates/firefox.tpl'
output_path = '~/.cache/wal/colors.json'

[templates.obsidian]
input_path = './templates/obsidian.tpl'
output_path = '~/.config/obsidian/snippets/matugen/theme.css'

[templates.qt5ct]
input_path = "~/.config/matugen/templates/qtct.tpl"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qtct.tpl"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.qt]
input_path = "~/.config/matugen/templates/Matugen.tpl"
output_path = "~/.local/share/color-schemes/Matugen.colors"

[templates.kde]
input_path = "~/.config/matugen/templates/kdeglobals.tpl"
output_path = "~/.config/kdeglobals"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.tpl"
output_path = '~/.config/gtk-3.0/generated-colors-matugen.css'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.tpl"
output_path = '~/.config/gtk-4.0/generated-colors-matugen.css'

[templates.btop]
input_path = "~/.config/matugen/templates/btop.tpl"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.calibre]
input_path = "~/.config/matugen/templates/calibre.tpl"
output_path = "~/.config/calibre/matugen.calibre-palette"
