---
- name: Unpack archive {{ item.name }}
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: "{{ item.remote_src | d(False) | bool }}"
    extra_opts: "{{ item.extra_opts | d([]) }}"
    include: "{{ item.include | d([]) }}"
