---
- name: Provision system
  hosts: all
  tasks:
    - name: Process module {{ module.name }}
      ansible.builtin.include_role:
        name: module
      loop: "{{ modules }}"
      loop_control:
        loop_var: module
      when: only_module is not defined or only_module == module.tag
