---
- name: Compute service filename (keep extension if present, else add .service)
  ansible.builtin.set_fact:
    svc_name: "{{ item.name if (item.name is search('\\.')) else item.name ~ '.service' }}"
- name: Create systemd service {{ item.name }}
  ansible.builtin.template:
    src: service.j2
    dest: /home/{{ ansible_user_id }}/.config/systemd/user/{{ svc_name }}
    mode: "{{ item.mode | d('0644') }}"
  become: "{{ item.become | d(False) | bool }}"
  notify:
    - reload systemctl
- name: Run handlers if any to reload the services
  ansible.builtin.meta: flush_handlers
- name: Enable service {{ item.name }}
  ansible.builtin.systemd:
    name: "{{ svc_name }}"
    enabled: true
    scope: "{{ item.scope | d('user') }}"
    force: true
  become: "{{ item.become | d(False) | bool }}"
  ignore_errors: "{{ ansible_check_mode }}"
