---
dotfiles_source_dir: "{{ playbook_dir }}/../files/framework/dots"
modules:
  - name: base_packages
    packages:
      - name: acpi
        state: latest
        source: pacman
      - name: pkgfile
        state: latest
        source: pacman
      - name: base-devel
        state: latest
        source: pacman
      - name: openssh
        state: latest
        source: pacman
      - name: git
        state: latest
        source: pacman
      - name: htop
        state: latest
        source: pacman
      - name: dnsutils
        state: latest
        source: pacman
      - name: traceroute
        state: latest
        source: pacman
      - name: powertop
        state: latest
        source: pacman
      - name: nmap
        state: latest
        source: pacman
      - name: tree
        state: latest
        source: pacman
      - name: unzip
        state: latest
        source: pacman
      - name: radeontop
        state: latest
        source: pacman
      - name: libva-utils
        state: latest
        source: pacman
      - name: wireless-regdb
        state: latest
        source: pacman
    line_in_file:
      - regexp: ^WIRELESS_REGDOM=.*
        line: WIRELESS_REGDOM="PL"
        path: /etc/conf.d/wireless-regdom
        become: true
  - name: browsers
    packages:
      - name: firefox
        state: latest
        source: pacman
  - name: terminal
    packages:
      - name: kitty
        state: latest
        source: pacman
    links:
      - src: "{{ dotfiles_source_dir }}/kitty"
        dest: "{{ configs_home }}/kitty"
  - name: dev
    packages:
      - name: golang
        source: asdf
        repository: https://github.com/kennyp/asdf-golang.git
        versions:
          - latest
        global: latest
      - name: python
        source: asdf
        repository: ""
        versions:
          - 3.9.0
        global: 3.9.0
      - name: nodejs
        source: asdf
        repository: https://github.com/asdf-vm/asdf-nodejs.git
        versions:
          - latest
        global: latest
      - name: rustup
        state: latest
        source: pacman
  - name: hyprland
    packages:
      - name: hyprpaper
        state: latest
        source: pacman
      - name: hyprland
        state: latest
        source: pacman
      - name: blueman-git
        state: latest
        source: aur
      - name: udiskie
        state: latest
        source: pacman
      - name: dolphin
        state: latest
        source: pacman
      - name: brightnessctl
        state: latest
        source: pacman
      - name: playerctl
        state: latest
        source: pacman
      - name: xdg-user-dirs
        state: latest
        source: pacman
      - name: xdg-desktop-portal-hyprland
        state: latest
        source: pacman
    users:
      - name: "{{ ansible_user_id }}"
        groups: video,input
    links:
      - src: "{{ dotfiles_source_dir }}/hypr"
        dest: "{{ configs_home }}/hypr"
      - src: "{{ dotfiles_source_dir }}/electron/electron-flags.conf"
        dest: "{{ configs_home }}/electron-flags.conf"
      - src: "{{ dotfiles_source_dir }}/xdg/user-dirs.dirs"
        dest: "{{ configs_home }}/user-dirs.dirs"
  - name: tmux
    packages:
      - name: tmux
        state: latest
        source: pacman
    git_repos:
      - repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ configs_home }}/tmux/plugins/tpm"
    links:
      - src: "{{ dotfiles_source_dir }}/tmux/tokyonight_night.tmux"
        dest: "{{ configs_home }}/tmux/tokyonight_night.tmux"
      - src: "{{ dotfiles_source_dir }}/tmux/.tmux.conf"
        dest: "{{ configs_home }}/tmux/tmux.conf"
      - src: "{{ linux_source_dir }}/bin/tmux-switch.sh"
        dest: "{{ binaries_home }}/tmux-switch.sh"
      - src: "{{ linux_source_dir }}/bin/tmux-window-switch.sh"
        dest: "{{ binaries_home }}/tmux-window-switch.sh"
      - src: "{{ linux_source_dir }}/bin/tmux-update-display.sh"
        dest: "{{ binaries_home }}/tmux-update-display.sh"
  - name: git
    git_config:
      - name: user.email
        value: filipmikina@gmail.com
        scope: global
      - name: user.name
        value: Filip Mikina
        scope: global
  - name: nvim
    git_config:
      - name: core.editor
        value: nvim
        scope: global
    packages:
      - name: fzf
        state: latest
        source: pacman
      - name: fd
        state: latest
        source: pacman
      - name: ripgrep
        state: latest
        source: pacman
      - name: lazygit
        state: latest
        source: pacman
      - name: neovim
        state: latest
        source: pacman
    links:
      - src: "{{ dotfiles_source_dir }}/nvim"
        dest: "{{ configs_home }}/nvim"
      - src: "{{ dotfiles_source_dir }}/lazygit/config.yaml"
        dest: "{{ configs_home }}/lazygit/config.yml"
  - name: zsh
    packages:
      - name: zsh
        source: pacman
        state: latest
      - name: zoxide
        source: asdf
        repository: https://github.com/nyrst/asdf-zoxide.git
        versions:
          - latest
        global: latest
      - name: exa
        source: asdf
        repository: https://github.com/nyrst/asdf-exa.git
        versions:
          - latest
        global: latest
    git_repos:
      - repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
      - repo: https://github.com/Aloxaf/fzf-tab.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-tab"
      - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      - repo: https://github.com/unixorn/fzf-zsh-plugin.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
        version: main
      - repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    users:
      - name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
    links:
      - src: "{{ dotfiles_source_dir }}/zsh/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
      - src: "{{ dotfiles_source_dir }}/zsh/.p10k.zsh"
        dest: "{{ ansible_env.HOME }}/.p10k.zsh"
      - src: "{{ dotfiles_source_dir }}/zsh/config.d"
        dest: "{{ configs_home }}/zsh/config.d"
      - src: "{{ dotfiles_source_dir }}/fzf/.fzf.zsh"
        dest: "{{ ansible_env.HOME }}/.fzf.zsh"
  - name: prep home layout
    directories:
      - path: "{{ repos.personal_home }}"
      - path: "{{ repos.external_home }}"
      - path: "{{ repos.work_home }}"
  - name: note taking
    packages:
      - name: obsidian
        state: latest
        source: pacman
    links:
      - src: "{{ linux_source_dir }}/bin/md-toc"
        dest: "{{ binaries_home }}/md-toc"
    git_repos:
      - repo: ssh://git@git.home:12222/fiffeek/brain.git
        dest: "{{ repos.personal_home }}/brain"
  - name: personal repos
    git_repos:
      - repo: ssh://git@git.home:12222/fiffeek/homelab.git
        dest: "{{ repos.personal_home }}/homelab"
        version: main
  - name: forks and external repos
    git_repos:
      - repo: git@github.com:fiffeek/searxng.git
        dest: "{{ repos.external_home }}/searxng"
  - name: misc scrips
    links:
      - src: "{{ linux_source_dir }}/bin/av_decrypt"
        dest: "{{ binaries_home }}/av_decrypt"
      - src: "{{ linux_source_dir }}/bin/av_encrypt"
        dest: "{{ binaries_home }}/av_encrypt"
      - src: "{{ linux_source_dir }}/bin/backup"
        dest: "{{ binaries_home }}/backup"
      - src: "{{ linux_source_dir }}/bin/kvm.sh"
        dest: "{{ binaries_home }}/kvm.sh"
