backend = "fastresize"
color_space = "labmixed"
palette = "dark16"
threshold = 12

[templates]
kitty.template = 'kitty.conf'
kitty.target = '~/.config/kitty/generated-colors.conf'

zsh.template = 'colors.zsh'
zsh.target = '~/.config/zsh/config.d/generated-colors.zsh'

matugen.template = 'matugen.tpl'
matugen.target = '~/.config/matugen/generated-colors'

nvim.template = 'pywal.tpl'
nvim.target = '~/.cache/wal/nvim.json'

vim.template = 'vim.tpl'
vim.target = '~/.cache/wal/colors-wal.vim'

btop.template = 'btop.tpl'
btop.target = '~/.config/btop/themes/wallust.theme'

yazi.template = 'yazi.tpl'
yazi.target = '~/.config/yazi/flavors/wallust.yazi/flavor.toml'

yazitmtheme.template = 'yazi.tmtheme.tpl'
yazitmtheme.target = '~/.config/yazi/flavors/wallust.yazi/tmtheme.xml'
