---
- name: Allow the user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: visudo -cf %s
- name: Ensure aur packages are managed {{ aur_packages | map(attribute='name') }}
  ansible.builtin.include_tasks: package.yaml
  with_items: "{{ aur_packages }}"
